apiVersion: enmasse.io/v1beta1
kind: Address
metadata:
  namespace: widgets
  name: widgetspace.warehouse
spec:
  address: warehouse
  plan: standard-small-subscription
  topic: orders
  type: subscription
  subscription:
    maxConsumers: 10
